# Generated by Django 3.1 on 2020-08-16 16:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('experience', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('specialty', models.CharField(choices=[('MATHAMATICS', 'MATH'), ('ENGLISH', 'ENG'), ('PHYSICS', 'PHY'), ('CHEMISTRY', 'CHM')], max_length=128)),
                ('photo', models.URLField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQOChe4AwTmVj262VJ5qEO57d_ZIxKddYQIhw&usqp=CAU')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
